config/routes.rb
SmileTeam::Application.routes.draw do
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  root :to => "home#index"

  resources :events do
    member do
      get "invite_all"
    end
  end

  match "/users" => "users#index",          via: :get,    as: :users
  match "/users" => "users#create",         via: :post,   as: :users
  match "/users/new" => "users#new",        via: :get,    as: :new_user
  match "/users/:id/edit" => "users#edit",  via: :get,    as: :edit_user
  match "/users/:id" => "users#show",       via: :get,    as: :user
  match "/users/:id" => "users#update",     via: :put,    as: :user
  match "/users/:id" => "users#destroy",    via: :delete, as: :user
  match "/users/:id/approve_join_request" => "users#approve_join_request",  via: :get, as: :approve_join_request
  match "/users/:id/reject_join_request" => "users#reject_join_request",    via: :get, as: :reject_join_request

  match "/team" => "groups#join_requests",           as: :join_requests
  match "/team/approve_all" => "groups#approve_all", as: :approve_all
  match "/team/reject_all" => "groups#reject_all",   as: :reject_all

  resource :invites, only: [:update]

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :users

  validates_uniqueness_of :name

  def captain
    self.users.where(site_role: "captain").first
  end

  def approve_all
    connection = ActiveRecord::Base.connection()
    connection.execute("update users set site_role='mate' where group_id=#{ActiveRecord::Base.sanitize(self.id)} and (site_role is null)")
  end

  def reject_all
    connection = ActiveRecord::Base.connection()
    connection.execute("update users set group_id=null where group_id=#{ActiveRecord::Base.sanitize(self.id)} and (site_role is null)")
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authorize_join_requests


  def join_requests
    @users = User.unapproved(current_user.group)
  end

  def approve_all
    res = current_user.group.approve_all
    puts res
    render :join_requests
  end

  def reject_all
    res = current_user.group.reject_all
    puts res
    render :join_requests
  end

private

  def authorize_join_requests
    authorize! :manage, :join_requests
  end
end

app/views/groups/join_requests.html.erb
<h1>Приём в команду</h1>
<div class="content">
  <%= link_to 'Принять всех', approve_all_path, id: "approve_button", class: "action_button" %>
  <%= link_to 'Отклонить всех', reject_all_path, id: "reject_button", class: "action_button" %>
  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>Имя</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <% if @users.present? %>
      <% @users.each do |user| %>
        <tbody>
        <tr>
          <td><%= user.show_name%></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Принять', approve_join_request_path(user), id: "approve_button", class: "action_button" %></td>
          <td><%= link_to 'Отклонить', reject_join_request_path(user), id: "reject_button", class: "action_button" %></td>
        </tr>
        </tbody>
      <% end %>
    <% end %>
  </table>


</div>