config/routes.rb
SmileTeam::Application.routes.draw do
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  root :to => "home#index"

  resources :events do
    member do
      get "invite_all"
    end
  end

  match "/users" => "users#index",          via: :get,    as: :users
  match "/users" => "users#create",         via: :post,   as: :users
  match "/users/new" => "users#new",        via: :get,    as: :new_user
  match "/users/:id/edit" => "users#edit",  via: :get,    as: :edit_user
  match "/users/:id" => "users#show",       via: :get,    as: :user
  match "/users/:id" => "users#update",     via: :put,    as: :user
  match "/users/:id" => "users#destroy",    via: :delete, as: :user
  match "/users/:id/approve_join_request" => "users#approve_join_request",  via: :get, as: :approve_join_request
  match "/users/:id/reject_join_request" => "users#reject_join_request",    via: :get, as: :reject_join_request

  match "/team" => "groups#join_requests",           as: :join_requests
  match "/team/approve_all" => "groups#approve_all", as: :approve_all
  match "/team/reject_all" => "groups#reject_all",   as: :reject_all

  resource :invites, only: [:update]

end

app/models/event.rb
class Event < ActiveRecord::Base

  has_one :game
  belongs_to :author, foreign_key: :author_id, class_name: "User"
  has_many :invites

  validates_presence_of :author

  accepts_nested_attributes_for :game

  class << self
    ##
    # Scope of events which start time is in future
    #
    def in_future
      self.where("start_date >= ?", Date.today)
    end

  end

  ##
  # Group of users which this event created for
  #
  def group
    self.author.group
  end

  ##
  # Create invite on current event for defined user
  #
  def invite(user)
    Invite.create(user_id: user.id, event_id: self.id, state: Invite::STATES[:sent]) if Invite.where(user_id: user.id, event_id: self.id).blank?
  end

  ##
  # Create invites on current event for all users in group
  #
  def invite_all
    self.group.users.each { |user| self.invite(user) }
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource :event
  load_and_authorize_resource :game

  # GET /events
  # GET /events.json
  def index
    @events = Event.in_future

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @event.game = Game.new
    @projects = Project.all
    @project_formats = ProjectFormat.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @projects = Project.all
    @project_formats = ProjectFormat.all
  end

  # POST /events
  # POST /events.json
  def create
    @event.author = current_user
    @event.event_type = "Game"
    @event.game.event = @event

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_path }
      format.json { head :ok }
    end
  end

  def invite_all
    @event.invite_all
    respond_to do |format|
      format.html { redirect_to events_path }
      format.js   { head :ok }
    end

  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="event">
    <div class="field">
      <%= f.label :name, "Название", class: "caption" %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :desc, "Описание", class: "caption" %>
      <%= f.text_area :desc %>
    </div>
    <div class="field datetime_select">
      <%= f.label :start_date, "Начало", class: "caption" %>
      <%= f.datetime_select :start_date, order: [:day, :month, :year, :hour, :minute] %>
    </div>
  </div>

  <%= f.fields_for :game do |gam| %>

    <%= render "games/form", f: gam, game: @event.game %>

  <% end %>

  <div class="actions">
    <%= f.submit "Сохранить", class: "action_button" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<%= render 'form' %>

<%= link_to 'Просмотр', @event, class: "action_button" %> |
<%= link_to 'Назад', events_path, class: "action_button" %>

app/views/events/index.html.erb
<h1>Новости</h1>

<div>
  <% if can? :manage, Event %>
    <%= link_to 'Новое событие', new_event_path, class: "nav_button" %>
  <% end %>
</div>

<% @events.each do |event| %>
  <% if event.event_type == "Game" %>
    <% if can? :read, event %>
      <div class="row game <%= event.game.css_class %>">
        <div class="span6">
          <% if can? :invite_all, event %>
            <%= link_to "Пригласить всех", invite_all_event_path(event), class: "action_button" %>
          <% end %>
          <%= render "games/game", event: event %>
        </div>
        <div class="span3 invites">
          <%= render "invites/index", event: event %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<%= render 'form' %>

<%= link_to 'Назад', events_path, class: "nav_button" %>

app/views/events/show.html.erb
<div class="row content">
  <div class="span4">
  <p>
    <b>Название:</b>
    <%= @event.name %>
  </p>

  <p>
    <b>Описание:</b>
    <%= @event.desc %>
  </p>

  <p>
    <b>Тип:</b>
    <%= @event.event_type %>
  </p>

  <p>
    <b>Начало:</b>
    <%= @event.start_date %>
  </p>

  <p>
    <b>Автор:</b>
    <%= @event.author.show_name %>
  </p>

  <%= render "games/show", game: @event.game %>

  </div>
  <div class="span4">
    <%= show_my_invite(current_user, @event.invites) %>

    <% @event.invites.each do |invite| %>
        <%= show_state_icon(invite, true) unless invite.user == current_user %>
    <% end %>
  </div>
</div>

<%= link_to 'Править', edit_event_path(@event), class: "action_button" if can? :manage, @event %>
<%= link_to 'Назад', events_path, class: "action_button" %>