config/routes.rb
SmileTeam::Application.routes.draw do
  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  root :to => "home#index"

  resources :events do
    member do
      get "invite_all"
    end
  end

  match "/users" => "users#index",          via: :get,    as: :users
  match "/users" => "users#create",         via: :post,   as: :users
  match "/users/new" => "users#new",        via: :get,    as: :new_user
  match "/users/:id/edit" => "users#edit",  via: :get,    as: :edit_user
  match "/users/:id" => "users#show",       via: :get,    as: :user
  match "/users/:id" => "users#update",     via: :put,    as: :user
  match "/users/:id" => "users#destroy",    via: :delete, as: :user
  match "/users/:id/approve_join_request" => "users#approve_join_request",  via: :get, as: :approve_join_request
  match "/users/:id/reject_join_request" => "users#reject_join_request",    via: :get, as: :reject_join_request

  match "/team" => "groups#join_requests",           as: :join_requests
  match "/team/approve_all" => "groups#approve_all", as: :approve_all
  match "/team/reject_all" => "groups#reject_all",   as: :reject_all

  resource :invites, only: [:update]

end

app/views/layouts/_control_panel.html.erb
<% if current_user.present? && !current_user.guest? %>
  <div id="admin_panel" class="nav">
    <ul>
      <div><b>Панель управления</b></div>
      <% if can? :read, User %>
        <li><a href="<%= users_path %>">Пользователи</a></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<div id="navigate" class="nav">
  <ul>
    <% if can? :read, Event %>
      <li><a href="<%= events_path %>">Новости</a></li>
    <% end %>
    <li><a href="#">О нас</a></li>
    <li><a href="http://fadzone.kiev.ua/forum">ФОРУМ</a></li>
  </ul>
</div>

app/views/layouts/_user_panel.html.erb
<div id="user_panel" class="nav">
  <ul>
    <% unless user_signed_in? %>
      <li><a href="<%= new_user_registration_path %>">Зарегистрироваться</a></li>
      <li><a href="<%= new_user_session_path %>">Войти</a></li>
    <% else %>
      <div><b><%= current_user.show_name %> (<%= current_user.site_role || "guest" %>)</b></div>
      <li><%= link_to "Личная страница", user_path(current_user) %></li>
      <li><a href="#">Сменить пароль</a></li>
      <% if can? :manage, :join_requests %>
        <li><%= link_to "Приём в команду", join_requests_path %></li>
      <% end %>
      <li><%= link_to "Выйти", destroy_user_session_path, :method => :delete %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>S.M.I.L.E.</title>
  <%= stylesheet_link_tag    "bootstrap/css/bootstrap" %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row-fluid">
  <div class="span12 header"><a href="/"><img src="/images/smile_sign.jpg"></a></div>
    <div class="row-fluid">
      <div class="span2">

        <%= render "layouts/user_panel" %>
        <br>
        <%= render "layouts/menu" %>
        <br>
        <%= render "layouts/control_panel" %>
      </div>
      <div class="span10">
        <%= show_flash %>

        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>